const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const Report = require('../models/Report');
const ScanResult = require('../models/ScanResult');
const logger = require('../config/logger');

const UPLOADS_DIR = path.join(__dirname, '../../uploads/reports');

const ensureDir = () => {
  if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });
};

const generateReport = async (reportId) => {
  ensureDir();
  const report = await Report.findById(reportId).populate('generatedBy', 'name email');
  if (!report) return;

  report.status = 'generating';
  await report.save();

  try {
    const results = await ScanResult.find({ orgId: report.orgId }).limit(100);
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const filename = `report_${reportId}_${Date.now()}.pdf`;
    const filePath = path.join(UPLOADS_DIR, filename);
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Header
    doc.fontSize(24).fillColor('#00E5FF').text('DataSentinel', 50, 50);
    doc.fontSize(18).fillColor('#333').text(report.title, 50, 85);
    doc.fontSize(10).fillColor('#666').text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 50, 115);
    doc.fontSize(10).text(`By: ${report.generatedBy?.name || 'System'}`, 50, 130);
    doc.moveTo(50, 150).lineTo(545, 150).stroke('#00E5FF');

    // Summary Section
    doc.moveDown(2);
    doc.fontSize(14).fillColor('#333').text('1. Executive Compliance Summary', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#555').text(`This report provides a comprehensive audit of the Personal Data Discovery and Classification activities for ${report.orgId}. Under the Digital Personal Data Protection Act (DPDPA) 2023, organizations are mandated to maintain accuracy and implement appropriate security safeguards for personal data.`);
    
    // Key Metrics Grid
    doc.moveDown(1);
    const criticalCount = results.filter(r => r.sensitivityLevel === 'sensitive_personal').length;
    const highCount = results.filter(r => r.sensitivityLevel === 'personal').length;
    const pendingRemediation = results.filter(r => r.remediationStatus === 'pending').length;

    doc.rect(50, doc.y, 495, 80).fill('#F8FAFC').stroke('#E2E8F0');
    doc.fillColor('#333').fontSize(10);
    doc.text('TOTAL ASSETS SCANNED', 70, doc.y + 15);
    doc.text('CRITICAL (SENSITIVE PERSONAL)', 210, doc.y);
    doc.text('PENDING REMEDIATION', 410, doc.y);
    
    doc.fontSize(20).fillColor('#00E5FF').text(String(results.length), 70, doc.y + 15);
    doc.fillColor('#FF4D6D').text(String(criticalCount), 210, doc.y);
    doc.fillColor('#FFB020').text(String(pendingRemediation), 410, doc.y);
    
    doc.moveDown(4);

    // DPDPA Section Alignment
    doc.fontSize(14).fillColor('#333').text('2. Regulatory Alignment (DPDPA 2023)', { underline: true });
    doc.moveDown(0.5);
    
    const alignment = [
      { section: 'Section 6', requirement: 'Consent Management', status: 'In Review' },
      { section: 'Section 8(5)', requirement: 'Security Safeguards', status: criticalCount > 0 ? 'Action Required' : 'Maintained' },
      { section: 'Section 8(6)', requirement: 'Breach Notification', status: 'Compliant' },
      { section: 'Section 12', requirement: 'Right to Erasure', status: 'Workflow Active' }
    ];

    alignment.forEach(item => {
      doc.fontSize(10).fillColor('#333').text(`${item.section}: ${item.requirement}`, { continued: true })
         .fillColor(item.status === 'Compliant' ? '#00FF9D' : '#FFB020').text(` — [${item.status}]`, { align: 'right' });
      doc.moveDown(0.5);
    });

    // Detailed Findings
    if (results.length > 0) {
      doc.moveDown(1.5);
      doc.fontSize(14).fillColor('#333').text('3. Detailed Data Inventory (Top Risks)', { underline: true });
      doc.moveDown(0.5);
      
      results.slice(0, 15).forEach((r, idx) => {
        doc.fontSize(9).fillColor('#444').text(`${idx + 1}. ${r.fileName} (${r.sensitivityLevel.toUpperCase()}) - Risk Score: ${r.riskScore}`);
        doc.fontSize(8).fillColor('#888').text(`   Path: ${r.assetPath} | PII Types: ${r.detectedPII.map(p => p.type).join(', ')}`);
        doc.moveDown(0.4);
      });
    }

    doc.moveDown(2);
    doc.fontSize(10).fillColor('#666').text('--- End of Report ---', { align: 'center' });
    doc.text('This document is electronically generated by DataSentinel Intelligence Engine.', { align: 'center', fontSize: 8 });

    doc.end();

    await new Promise((resolve, reject) => {
      stream.on('finish', resolve);
      stream.on('error', reject);
    });

    report.status = 'ready';
    report.fileUrl = `/uploads/reports/${filename}`;
    report.content = { summary: `${results.length} assets analyzed`, criticalCount, highCount };
    await report.save();

  } catch (err) {
    logger.error('Report generation error:', err);
    report.status = 'failed';
    await report.save();
  }
};

module.exports = { generateReport };
